demo:
  hi: 你好
  hello: hello
  test: ${demo.hello},${demo.hi}
  num1: ${random.int(20)}

#debug: true

#spring:
#  output:
#    ansi:
#      enabled: detect      #如果设备支出ANSI,则采用多彩输出方式打印日志

#logging:
#  file:
#    path: my.log      #保存在当前项目根目录下`
logging:
  #  file:
  #   path: /var/log     #保存在项目所在盘根目录
  level.com.example.demo.controller.TestController: WARN        #指定logger的输出级别

validationQuery: select 1
mysql:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://192.168.6.41:3306/test?useUnicode=true&characterEncoding=UTF-8
  username: mysql
  password: nJDNZtWsJJdftbYGrVOB
  maxActive: 20

spring:
  main:
    #当遇到同样名字的时候，是否允许覆盖注册
    allow-bean-definition-overriding: true

  redis:
    database: 0       # Redis数据库索引（默认为0）
    host: localhost   # Redis服务器地址
    port: 6379        # Redis服务器连接端口
    password:         # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8     # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8       # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
    timeout: 20000          # 连接超时时间（毫秒）




# 开启swagger
swagger:
  enabled: true
